# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib a5px, .registration = TRUE
NULL

#' Forward-aggregate a (Cloud-Optimised) GeoTIFF into A5 cells.
#'
#' @param src Path or URL string (file://, http(s)://, s3://, gs://, az://).
#' @param resolution A5 resolution (0--30).
#' @param stats Character vector of stats: subset of "mean", "sum", "count",
#'   "min", "max". Length-1 behaves identically to the previous scalar API.
#' @param bands_idx 1-based band indices to read. Empty = all (unless
#'   bands_names is non-empty).
#' @param bands_names Band names to read (matched against the GDAL DESCRIPTION
#'   tag, falling back to band_NN). Empty = all (unless bands_idx is non-empty).
#' @param threads Worker threads (currently used for tile-level concurrency).
#' @param io_concurrency Number of tiles fetched concurrently.
#' @param overview_target_m A5 cell edge length in metres; when > 0 a COG
#'   overview that still oversamples the cell is read instead of full
#'   resolution. 0 disables overview use (always read IFD 0).
#' @param dequant_lut Pre-aggregation decode LUT over the integer code domain
#'   starting at `dequant_min`; empty = no dequantization.
#' @param dequant_min First code covered by `dequant_lut`.
#' @returns A list with `cell` (b1..b8 raw fields), `bands` (named numeric
#'   vectors; key form is `<band>` for length-1 stats and `<band>__<stat>`
#'   for length>1), `band_names`, and `stats` (character).
#' @noRd
#' @keywords internal
a5_read_raster_rs <- function(src, resolution, stats, bands_idx, bands_names, bbox, src_nodata, cpu_workers, io_concurrency, overview_target_m, dequant_lut, dequant_min, overlay, subsamples, cell_edge_m) .Call(wrap__a5_read_raster_rs, src, resolution, stats, bands_idx, bands_names, bbox, src_nodata, cpu_workers, io_concurrency, overview_target_m, dequant_lut, dequant_min, overlay, subsamples, cell_edge_m)

#' Forward-aggregate a (Cloud-Optimised) GeoTIFF into A5 cells, returning a
#' flat cell-major numeric buffer suitable for direct construction of an
#' Arrow `FixedSizeList<float64, n_bands>` array on the R side.
#'
#' @param src Path or URL string.
#' @param resolution A5 resolution (0--30).
#' @param stats Character vector of stats (subset of mean/sum/count/min/max).
#' @param bands_idx 1-based band indices to read (empty for all unless
#'   `bands_names` is provided).
#' @param bands_names Band names to read (matched against the GDAL
#'   DESCRIPTION tag).
#' @param threads Worker threads.
#' @param io_concurrency Number of tiles fetched concurrently.
#' @param overview_target_m A5 cell edge length in metres; when > 0 a COG
#'   overview that still oversamples the cell is read instead of full
#'   resolution. 0 disables overview use (always read IFD 0).
#' @returns A list with `cell` (b1..b8 raw), `value_flat` (named list of
#'   numeric vectors, one per stat in `stats` order, each of length
#'   `n_cells * n_bands` cell-major), `band_names`, `stats`, `n_bands`.
#' @noRd
#' @keywords internal
a5_read_raster_flat_rs <- function(src, resolution, stats, bands_idx, bands_names, bbox, src_nodata, cpu_workers, io_concurrency, overview_target_m, dequant_lut, dequant_min, overlay, subsamples, cell_edge_m) .Call(wrap__a5_read_raster_flat_rs, src, resolution, stats, bands_idx, bands_names, bbox, src_nodata, cpu_workers, io_concurrency, overview_target_m, dequant_lut, dequant_min, overlay, subsamples, cell_edge_m)

#' Forward-aggregate a (Cloud-Optimised) GeoTIFF straight into a Parquet
#' file. RecordBatch construction and Parquet write happen in Rust without
#' the R Arrow round-trip — appropriate for large embedding rasters where
#' the per-cell list-of-vectors materialisation in R becomes a bottleneck.
#'
#' @param src Path or URL string.
#' @param dest Output Parquet path.
#' @param resolution A5 resolution (0--30).
#' @param stats Character vector of stats (subset of mean/sum/count/min/max).
#' @param bands_idx,bands_names Band selection (see `a5_read_raster_rs`).
#' @param value_type Storage type for the value column ("float64" | "float32").
#' @param compression Parquet compression codec ("zstd" | "snappy" | "none").
#' @param threads Worker threads.
#' @param io_concurrency Number of tiles fetched concurrently.
#' @param overview_target_m A5 cell edge length in metres; when > 0 a COG
#'   overview that still oversamples the cell is read instead of full
#'   resolution. 0 disables overview use (always read IFD 0).
#' @returns The destination path (character scalar) on success.
#' @noRd
#' @keywords internal
a5_raster_to_parquet_rs <- function(src, dest, resolution, stats, bands_idx, bands_names, bbox, src_nodata, as_vector, value_type, compression, cpu_workers, io_concurrency, overview_target_m, dequant_lut, dequant_min, overlay, subsamples, cell_edge_m) .Call(wrap__a5_raster_to_parquet_rs, src, dest, resolution, stats, bands_idx, bands_names, bbox, src_nodata, as_vector, value_type, compression, cpu_workers, io_concurrency, overview_target_m, dequant_lut, dequant_min, overlay, subsamples, cell_edge_m)

#' Sample one pixel value per A5 cell. Inverse / cell-driven path.
#'
#' @param src Path or URL string.
#' @param cells_raw a5R-style cell list (b1..b8 raw fields).
#' @param bands_idx,bands_names Band selection.
#' @param src_nodata Length-1 vec or empty for no override.
#' @param threads,io_concurrency See `a5_read_raster_rs`.
#' @returns A list with `cell` (b1..b8 raw), `bands` (named numeric), and
#'   `band_names`.
#' @noRd
#' @keywords internal
a5_sample_at_cells_rs <- function(src, cells_raw, bands_idx, bands_names, src_nodata, cpu_workers, io_concurrency, dequant_lut, dequant_min) .Call(wrap__a5_sample_at_cells_rs, src, cells_raw, bands_idx, bands_names, src_nodata, cpu_workers, io_concurrency, dequant_lut, dequant_min)

#' Compute the WGS84 lon/lat bbox of the raster at `src`, by projecting the
#' 4 corners + 4 edge midpoints of the raster's projected extent into
#' WGS84 and taking the axis-aligned envelope.
#' @returns `c(xmin, ymin, xmax, ymax)`.
#' @noRd
#' @keywords internal
a5_raster_bbox_lonlat_rs <- function(src) .Call(wrap__a5_raster_bbox_lonlat_rs, src)

#' Diagnostic: the IFD index `a5_read_raster_rs` would read for the given
#' `overview_target_m` (the A5 cell edge in metres; 0 = overviews disabled).
#' 0 means full resolution. Exposed for testing / introspection.
#' @noRd
#' @keywords internal
a5_select_overview_level_rs <- function(src, overview_target_m) .Call(wrap__a5_select_overview_level_rs, src, overview_target_m)

# nolint end
