# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib a5cog, .registration = TRUE
NULL

a5cog_set_threads_rs <- function(n) .Call(wrap__a5cog_set_threads_rs, n)

a5cog_get_threads_rs <- function() .Call(wrap__a5cog_get_threads_rs)

#' Forward-aggregate a (Cloud-Optimised) GeoTIFF into A5 cells.
#'
#' @param src Path or URL string (file://, http(s)://, s3://, gs://, az://).
#' @param resolution A5 resolution (0--30).
#' @param stat One of "mean", "sum", "count", "min", "max".
#' @param threads Worker threads (currently used for tile-level concurrency).
#' @param io_concurrency Number of tiles fetched concurrently.
#' @returns A list with `cell` (b1..b8 raw fields), `bands` (named numeric
#'   vectors per band), and `band_names` (character).
#' @noRd
#' @keywords internal
a5_read_raster_rs <- function(src, resolution, stat, threads, io_concurrency) .Call(wrap__a5_read_raster_rs, src, resolution, stat, threads, io_concurrency)

# nolint end
